# This is a config for E2B sandbox template.
# You can use template ID (6y19qe419m1zt63uwv9s) or template name (codesheet-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codesheet-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("codesheet-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codesheet-nextjs-test')

team_id = "17baf643-cba4-4709-8402-9ff47073f216"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codesheet-nextjs-test"
template_id = "6y19qe419m1zt63uwv9s"
